name: Bug Report
description: Create a report to help us improve
labels: 'bug :beetle:'
body:

- type: input
  attributes:
    label: "Xmake 版本"
    description: "你正在使用的 Xmake 版本是什么？"
    placeholder: 0.0.0
  validations:
    required: true
- type: input
  attributes:
    label: "操作系统版本和架构"
  validations:
    required: true
